/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import com.mysql.cj.x.protobuf.MysqlxDatatypes;
import java.awt.HeadlessException;
import java.awt.event.MouseListener;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Dhananjaya
 */
public class Login extends javax.swing.JFrame {
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    

    /**
     * Creates new form Login
     */
    public static String logType;
    int mousepX;
    int mousepY;
    public Login() {
        super("Login");
        initComponents();
        this.setLocationRelativeTo(null);
        conn = DBconnection.connection();
        jBody.setVisible(false);
        jLogout.setVisible(false);
        
       
        
        
        
         
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplatform = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jbtnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jChkLogin = new javax.swing.JCheckBox();
        jHedder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLogout = new javax.swing.JLabel();
        jBody = new javax.swing.JPanel();
        jmenu2 = new javax.swing.JLabel();
        jmenu1 = new javax.swing.JLabel();
        jmenu = new javax.swing.JLabel();
        jmenu3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplatform.setBackground(new java.awt.Color(255, 255, 255));
        jplatform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplatform.setForeground(new java.awt.Color(255, 255, 255));
        jplatform.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/account_circle.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-24-key.png"))); // NOI18N

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setBorder(null);

        jbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login_ON.png"))); // NOI18N
        jbtnLogin.setBorder(null);
        jbtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLogin.setOpaque(false);
        jbtnLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login_OFF.png"))); // NOI18N
        jbtnLogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login_ON.png"))); // NOI18N
        jbtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLoginMouseClicked(evt);
            }
        });
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/account_circle_x32.png"))); // NOI18N

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("User Name");

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Password");

        jChkLogin.setForeground(new java.awt.Color(153, 0, 153));
        jChkLogin.setText("Login as a Gust");
        jChkLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplatformLayout = new javax.swing.GroupLayout(jplatform);
        jplatform.setLayout(jplatformLayout);
        jplatformLayout.setHorizontalGroup(
            jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplatformLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jplatformLayout.createSequentialGroup()
                .addGroup(jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplatformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplatformLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplatformLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplatformLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jplatformLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jplatformLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jChkLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jplatformLayout.setVerticalGroup(
            jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplatformLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplatformLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplatformLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jplatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplatformLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jChkLogin)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jplatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 400));

        jHedder.setBackground(new java.awt.Color(255, 255, 255));
        jHedder.setForeground(new java.awt.Color(255, 255, 255));
        jHedder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jHedderMouseDragged(evt);
            }
        });
        jHedder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jHedderMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 0, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Advanced Level Student Management System");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/expand_arrow_x32.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cross_x32.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLogout.setForeground(new java.awt.Color(153, 0, 153));
        jLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogout.setText("Logout");
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jHedderLayout = new javax.swing.GroupLayout(jHedder);
        jHedder.setLayout(jHedderLayout);
        jHedderLayout.setHorizontalGroup(
            jHedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHedderLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jHedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHedderLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHedderLayout.createSequentialGroup()
                        .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addContainerGap())))
        );
        jHedderLayout.setVerticalGroup(
            jHedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHedderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHedderLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jHedderLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jHedderLayout.createSequentialGroup()
                        .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jHedder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 741, 100));

        jBody.setBackground(new java.awt.Color(255, 255, 255));
        jBody.setForeground(new java.awt.Color(255, 255, 255));

        jmenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sesrch_user_x100.png"))); // NOI18N
        jmenu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jmenu2MouseMoved(evt);
            }
        });
        jmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenu2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenu2MouseExited(evt);
            }
        });

        jmenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_user_x100.png"))); // NOI18N
        jmenu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jmenu1MouseMoved(evt);
            }
        });
        jmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenu1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenu1MouseExited(evt);
            }
        });

        jmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/remove_user_x100.png"))); // NOI18N
        jmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jmenuMouseMoved(evt);
            }
        });
        jmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenuMouseExited(evt);
            }
        });

        jmenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/settings_x100.png"))); // NOI18N
        jmenu3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jmenu3MouseMoved(evt);
            }
        });
        jmenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenu3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenu3MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(155, 0, 155));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTATION");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(155, 0, 155));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("STUDENT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(155, 0, 155));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SETTINGS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(155, 0, 155));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LEAVING");

        javax.swing.GroupLayout jBodyLayout = new javax.swing.GroupLayout(jBody);
        jBody.setLayout(jBodyLayout);
        jBodyLayout.setHorizontalGroup(
            jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBodyLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBodyLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBodyLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jBodyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jBodyLayout.createSequentialGroup()
                            .addComponent(jmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jBodyLayout.createSequentialGroup()
                            .addComponent(jmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jBodyLayout.setVerticalGroup(
            jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBodyLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jBodyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150)
                .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jBodyLayout.createSequentialGroup()
                    .addGap(0, 25, Short.MAX_VALUE)
                    .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 25, Short.MAX_VALUE)))
        );

        getContentPane().add(jBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 490, 400));

        setSize(new java.awt.Dimension(741, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
      
        if(jChkLogin.isSelected()){
            logType = "gust";
           
            System.out.println(logType);
        try {
            
            stmt = conn.createStatement();
            HashCode hc = new HashCode();
            String userName =  txtUser.getText();
            //String userPass = md5(txtPass.getPassword());
            String userPass = txtPass.getText();
        
            //System.out.println(userPass);
            
            String sql = "SELECT * FROM gust WHERE username = '"+userName+"' && password = '"+userPass+"'";
            
            rs = stmt.executeQuery(sql);
            if(rs.next()){             
               // setVisible(false);
               
               
               jChkLogin.setSelected(false);
               jBody.setVisible(true);
               jbtnLogin.setEnabled(false);
               jLogout.setVisible(true);
               txtUser.setText("");
               txtPass.setText("");
               jmenu1.setEnabled(false);
               jmenu3.setEnabled(false);
                                                    
            }else{          
                JOptionPane.showMessageDialog(null, "Password or Username invalied");
                txtUser.setText("");
                txtPass.setText("");
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }else{
        try {
            logType = "admin";
            
            stmt = conn.createStatement();
            HashCode hc = new HashCode();
            String userName =  txtUser.getText();
            //String userPass = md5(txtPass.getPassword());
            String userPass = hc.hashPass(txtPass.getText());
        
            //System.out.println(userPass);
            
            String sql = "SELECT * FROM admin WHERE username = '"+userName+"' && password = '"+userPass+"'";
            
            rs = stmt.executeQuery(sql);
            if(rs.next()){             
               // setVisible(false);
               jBody.setVisible(true);
               jbtnLogin.setEnabled(false);
               jLogout.setVisible(true);
               txtUser.setText("");
               txtPass.setText("");
               
               
                                                    
            }else{          
                JOptionPane.showMessageDialog(null, "Password or Username invalied");
                txtUser.setText("");
                txtPass.setText("");
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu1MouseExited
        jmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jmenu1MouseExited

    private void jmenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu1MouseClicked

        if(logType==("gust")){
            setVisible(true);
        Register rs = new Register();
        rs.setVisible(false);
        
        }else{
       
            setVisible(false);
            Register rs = new Register();
            rs.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jmenu1MouseClicked

    private void jmenu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu1MouseMoved
        jmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,0,153)));
    }//GEN-LAST:event_jmenu1MouseMoved

    private void jmenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu3MouseExited
        jmenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jmenu3MouseExited

    private void jmenu3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu3MouseMoved
        jmenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,0,153)));
    }//GEN-LAST:event_jmenu3MouseMoved

    private void jmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuMouseExited
        jmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jmenuMouseExited

    private void jmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuMouseMoved
        jmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,0,153)));
    }//GEN-LAST:event_jmenuMouseMoved

    private void jmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu2MouseExited
        jmenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jmenu2MouseExited

    private void jmenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu2MouseClicked
        setVisible(false);
        Student st = new Student();
        st.setVisible(true);
    }//GEN-LAST:event_jmenu2MouseClicked

    private void jmenu2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu2MouseMoved
        jmenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,0,153)));
    }//GEN-LAST:event_jmenu2MouseMoved

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
    System.exit(0);
} 
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        student_leaving s_l = new student_leaving();
        s_l.setVisible(true);
        
        
    }//GEN-LAST:event_jmenuMouseClicked

    private void jHedderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHedderMouseDragged
        int cordinatX = evt.getXOnScreen();
        int cordinatY = evt.getYOnScreen();
        
        this.setLocation(cordinatX-mousepX,cordinatY-mousepY);
        
       
    }//GEN-LAST:event_jHedderMouseDragged

    private void jHedderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHedderMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
      
    }//GEN-LAST:event_jHedderMousePressed

    private void jmenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu3MouseClicked
        if(logType == ("gust")){
        
            setVisible(true);
            Settings set = new Settings();
            set.setVisible(false);
        }else{
            setVisible(false);
            Settings set = new Settings();
            set.setVisible(true);
        }
        
    }//GEN-LAST:event_jmenu3MouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
     jLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,0,153)));        
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseExited
      jLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jLogoutMouseExited

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Do you Want to Logout?", "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        jLogout.setVisible(false);
        jBody.setVisible(false);
        jplatform.setVisible(true);
        jbtnLogin.setEnabled(true);
        jmenu1.setEnabled(true);
        jmenu3.setEnabled(true);
        
        }
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jChkLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkLoginActionPerformed

    private void jbtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLoginMouseClicked
        // TODO add your handling code here:
        System.out.println("HIIIIII");
    }//GEN-LAST:event_jbtnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jBody;
    private javax.swing.JCheckBox jChkLogin;
    private javax.swing.JPanel jHedder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLogout;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jmenu;
    public javax.swing.JLabel jmenu1;
    private javax.swing.JLabel jmenu2;
    public javax.swing.JLabel jmenu3;
    public javax.swing.JPanel jplatform;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
